{% set name = "foamlib" %}
{% set version = "0.6.11" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/foamlib-{{ version }}.tar.gz
  sha256: 0240754fe822a4fdc1335fab171757d7e0f86950c5b87813ce3d60bc948d0858

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.7
    - setuptools >=61.2
    - pip
  run:
    - python >=3.7
    - aioshutil >=1,<2
    - pyparsing >=3,<4
    - typing_extensions >=4,<5

test:
  imports:
    - foamlib
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/gerlero/foamlib
  summary: A Python interface for interacting with OpenFOAM
  license: GPL-3.0-or-later
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - gerlero
