{% set name = "foamlib" %}
{% set version = "1.1.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/foamlib-{{ version }}.tar.gz
  sha256: d154962d4a3df81e4d2b4b9296deff4290fd55263836cbbadaa9f66a780eaa0a

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - hatchling
    - pip
  run:
    - python >={{ python_min }}
    - aioshutil >=1,<2
    - numpy >=1,<3
    - pyparsing >=3.1.2,<4
    - rich >=13,<15
    - typing_extensions >=4,<5

test:
  imports:
    - foamlib
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/gerlero/foamlib
  summary: A Python interface for interacting with OpenFOAM
  license: GPL-3.0-or-later
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - gerlero
