{% set name = "foamlib" %}
{% set version = "1.3.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/foamlib-{{ version }}.tar.gz
  sha256: fb061ee6d2152228e20edcafffdb95bc580326e0c03dd3f5cf753c663920b27d

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - uv-build >=0.8.14,<0.9
    - pip
  run:
    - python >={{ python_min }}
    - aioshutil >=1,<2
    - multicollections >=1,<2
    - numpy >=1,<3
    - pyparsing >=3.1.2,<4
    - rich >=13,<15
    - typing_extensions >=4.4,<5

test:
  imports:
    - foamlib
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/gerlero/foamlib
  summary: A Python interface for interacting with OpenFOAM
  license: GPL-3.0-or-later
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - gerlero
