{% set name = "foamlib" %}
{% set version = "0.8.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/foamlib-{{ version }}.tar.gz
  sha256: 221714187739590dd4ab43486479838301c560c8d238cb30af97bf2ab9e9f909

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python 3.7
    - hatchling
    - pip
  run:
    - python >=3.7
    - aioshutil >=1,<2
    - numpy >=1,<3
    - pyparsing >=3,<4
    - typing_extensions >=4,<5

test:
  imports:
    - foamlib
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/gerlero/foamlib
  summary: A Python interface for interacting with OpenFOAM
  license: GPL-3.0-or-later
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - gerlero
