{% set name = "foamlib" %}
{% set version = "1.3.21" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/foamlib-{{ version }}.tar.gz
  sha256: b101b8f5551940938f4437f51d9e8dd989639310a3184886a3db75f2bd297667

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - uv-build >=0.9,<0.10
    - pip
  run:
    - python >={{ python_min }}
    - aioshutil >=1,<2
    - multicollections >=1.0.4,<2
    - numpy >=1,<3
    - pyparsing >=3.1.2,<4
    - rich >=13,<15
    - typing_extensions >=4.5,<5

test:
  imports:
    - foamlib
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/gerlero/foamlib
  summary: A Python interface for interacting with OpenFOAM
  license: GPL-3.0-or-later
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - gerlero
